
server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/E-BANK?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
jwt:
  secretKey: +z5xzNpAhGAq1hFuKrbLM1L137V3+95vSbCgitrByZxSBfvnzzbn8RrAcybKmGxD


